version: '3'
services:
  frontpage-service:
    build: ../frontpage-service
    image: ardalo-digital-platform/frontpage-service:latest
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: local
